version: "3"
services:
  app:
    build: .
    command: make --no-print-directory run
    volumes:
      - ./src/goexample:/workspace/src/goexample
    environment:
      CODE_ENV: dev
    ports:
      - "18770:18770"
    # logging:
    #   driver: "json-file"
